export const ARTICLES_LOADING = 'ARTICLES_LOADING';
export const ADD_ARTICLES = 'ADD_ARTICLES';
export const ARTICLES_FAILED = 'ARTICLES_FAILED';

export const SHOWS_LOADING = 'SHOWS_LOADING';
export const ADD_SHOWS = 'ADD_SHOWS';
export const SHOWS_FAILED = 'SHOWS_FAILED';

export const ADD_INTERESTED = 'ADD_INTERESTED';
export const DELETE_INTERESTED = 'DELETE_INTERESTED';

export const SHOP_LOADING = 'SHOP_LOADING';
export const ADD_SHOP = 'ADD_SHOP';
export const SHOP_FAILED = 'SHOP_FAILED';

export const ADD_CART = 'ADD_CART';
export const DELETE_CART = 'DELETE_CART';